window.ORIVEA_CONFIG = {
  "brand": "ORIVÈA",
  "domain": "https://orivea.nl",
  "contactEmail": "shop@orivea.nl",
  "shippingCost": 6.95,
  "freeShippingFrom": 99,
  "minimumOrderAmount": 20,
  "paymentEnabled": false,
  "currency": "EUR",
  "emailJs": {
    "serviceId": "service_r55nwxz",
    "publicKey": "w3x9SY9OqatVgYJOw",
    "orderTemplate": "template_u5h46h4",
    "contactTemplate": "template_ehokbkn"
  }
};

window.ORIVEA_PRODUCTS = [
  {
    "id": "545",
    "glantierNummer": "545",
    "naam": "Glantier No. 545",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Elegant",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Chance Eau Fraiche",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "545",
      "chance eau fraiche",
      "chanel",
      "dames",
      "elegant",
      "fris",
      "fris - elegant"
    ]
  },
  {
    "id": "578",
    "glantierNummer": "578",
    "naam": "Glantier No. 578",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Bloemig",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Coco Mademoiselle",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "578",
      "bestseller",
      "chanel",
      "chypre - bloemig",
      "coco mademoiselle",
      "dames"
    ]
  },
  {
    "id": "559",
    "glantierNummer": "559",
    "naam": "Glantier No. 559",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Gourmand",
    "merkReferentie": "Lancome",
    "parfumReferentie": "La Vie Est Belle",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - gourmand karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "559",
      "bestseller",
      "dames",
      "la vie est belle",
      "lancome",
      "zoet",
      "zoet - gourmand"
    ]
  },
  {
    "id": "570",
    "glantierNummer": "570",
    "naam": "Glantier No. 570",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Oriëntaals - Warm",
    "merkReferentie": "Yves Saint Laurent",
    "parfumReferentie": "Libre",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een oriëntaals - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "570",
      "dames",
      "libre",
      "luxe",
      "oriëntaals - warm",
      "warm",
      "yves saint laurent"
    ]
  },
  {
    "id": "607",
    "glantierNummer": "607",
    "naam": "Glantier No. 607",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Oriëntaals - Vanille",
    "merkReferentie": "Yves Saint Laurent",
    "parfumReferentie": "Black Opium",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een oriëntaals - vanille karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "607",
      "avond",
      "black opium",
      "dames",
      "oriëntaals - vanille",
      "yves saint laurent"
    ]
  },
  {
    "id": "553",
    "glantierNummer": "553",
    "naam": "Glantier No. 553",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Oriëntaals - Bloemig",
    "merkReferentie": "Carolina Herrera",
    "parfumReferentie": "Good Girl",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een oriëntaals - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "553",
      "carolina herrera",
      "dames",
      "good girl",
      "oriëntaals - bloemig"
    ]
  },
  {
    "id": "602",
    "glantierNummer": "602",
    "naam": "Glantier No. 602",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Floraal",
    "merkReferentie": "Carolina Herrera",
    "parfumReferentie": "Good Girl",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - floraal karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "602",
      "carolina herrera",
      "chypre - floraal",
      "dames",
      "good girl",
      "premium"
    ]
  },
  {
    "id": "401",
    "glantierNummer": "401",
    "naam": "Glantier No. 401",
    "type": "Parfum Premium P",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Premium - Floraal",
    "merkReferentie": "Glantier",
    "parfumReferentie": "Premium 401",
    "premiumBeschikbaar": true,
    "prijs": 17,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een premium - floraal karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "401",
      "dames",
      "glantier",
      "nieuw",
      "premium",
      "premium - floraal",
      "premium 401"
    ]
  },
  {
    "id": "402",
    "glantierNummer": "402",
    "naam": "Glantier No. 402",
    "type": "Parfum Premium P",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Premium - Fruitig",
    "merkReferentie": "Glantier",
    "parfumReferentie": "Premium 402",
    "premiumBeschikbaar": true,
    "prijs": 17,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een premium - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "402",
      "dames",
      "glantier",
      "premium",
      "premium - fruitig",
      "premium 402"
    ]
  },
  {
    "id": "403",
    "glantierNummer": "403",
    "naam": "Glantier No. 403",
    "type": "Parfum Premium P",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Premium - Romantisch",
    "merkReferentie": "Glantier",
    "parfumReferentie": "Premium 403",
    "premiumBeschikbaar": true,
    "prijs": 17,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een premium - romantisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "403",
      "dames",
      "glantier",
      "premium",
      "premium - romantisch",
      "premium 403"
    ]
  },
  {
    "id": "759",
    "glantierNummer": "759",
    "naam": "Glantier No. 759",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Kruidig",
    "merkReferentie": "Paco Rabanne",
    "parfumReferentie": "1 Million",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - kruidig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "1 million",
      "759",
      "bestseller",
      "heren",
      "houtachtig - kruidig",
      "one million",
      "paco rabanne"
    ]
  },
  {
    "id": "771",
    "glantierNummer": "771",
    "naam": "Glantier No. 771",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Fris - Kruidig",
    "merkReferentie": "Dior",
    "parfumReferentie": "Sauvage",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - kruidig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "771",
      "bestseller",
      "dior",
      "dior sauvage",
      "fris - kruidig",
      "heren",
      "sauvage"
    ]
  },
  {
    "id": "791",
    "glantierNummer": "791",
    "naam": "Glantier No. 791",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Intens - Aromatisch",
    "merkReferentie": "Dior",
    "parfumReferentie": "Sauvage Elixir",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-premium-heren.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een intens - aromatisch karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "791",
      "dior",
      "elixir",
      "heren",
      "intens - aromatisch",
      "premium",
      "sauvage",
      "sauvage elixir"
    ]
  },
  {
    "id": "743",
    "glantierNummer": "743",
    "naam": "Glantier No. 743",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Aromatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Bleu de Chanel",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - aromatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "743",
      "bleu",
      "bleu de chanel",
      "chanel",
      "heren",
      "houtachtig - aromatisch"
    ]
  },
  {
    "id": "777",
    "glantierNummer": "777",
    "naam": "Glantier No. 777",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Warm - Verleidelijk",
    "merkReferentie": "Jean Paul Gaultier",
    "parfumReferentie": "Le Male",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een warm - verleidelijk karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "777",
      "heren",
      "jean paul gaultier",
      "le male",
      "warm - verleidelijk"
    ]
  },
  {
    "id": "788",
    "glantierNummer": "788",
    "naam": "Glantier No. 788",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Aquatisch - Krachtig",
    "merkReferentie": "Paco Rabanne",
    "parfumReferentie": "Invictus",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een aquatisch - krachtig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "788",
      "aquatisch - krachtig",
      "heren",
      "invictus",
      "paco rabanne",
      "sportief"
    ]
  },
  {
    "id": "706",
    "glantierNummer": "706",
    "naam": "Glantier No. 706",
    "type": "Parfum Premium P",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Premium - Elegant",
    "merkReferentie": "Glantier",
    "parfumReferentie": "Premium 706",
    "premiumBeschikbaar": true,
    "prijs": 17,
    "image": "assets/images/glantier-premium-heren.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een premium - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "706",
      "glantier",
      "heren",
      "premium",
      "premium - elegant",
      "premium 706"
    ]
  },
  {
    "id": "707",
    "glantierNummer": "707",
    "naam": "Glantier No. 707",
    "type": "Parfum Premium P",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Aromatisch",
    "merkReferentie": "Glantier",
    "parfumReferentie": "Premium 707",
    "premiumBeschikbaar": true,
    "prijs": 17,
    "image": "assets/images/glantier-premium-heren.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - aromatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "707",
      "glantier",
      "heren",
      "houtachtig",
      "houtachtig - aromatisch",
      "premium",
      "premium 707"
    ]
  },
  {
    "id": "724",
    "glantierNummer": "724",
    "naam": "Glantier No. 724",
    "type": "Parfum Premium P",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Premium - Kruidig",
    "merkReferentie": "Glantier",
    "parfumReferentie": "Premium 724",
    "premiumBeschikbaar": true,
    "prijs": 17,
    "image": "assets/images/glantier-premium-heren.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een premium - kruidig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "724",
      "glantier",
      "heren",
      "kruidig",
      "premium",
      "premium - kruidig",
      "premium 724"
    ]
  },
  {
    "id": "501",
    "glantierNummer": "501",
    "naam": "Glantier No. 501",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "501",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "502",
    "glantierNummer": "502",
    "naam": "Glantier No. 502",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "502",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "503",
    "glantierNummer": "503",
    "naam": "Glantier No. 503",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Romantisch - Roos",
    "merkReferentie": "Chloe",
    "parfumReferentie": "Chloe",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een romantisch - roos karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "503",
      "chloe",
      "dames",
      "romantisch - roos"
    ]
  },
  {
    "id": "504",
    "glantierNummer": "504",
    "naam": "Glantier No. 504",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "504",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "505",
    "glantierNummer": "505",
    "naam": "Glantier No. 505",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "505",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "506",
    "glantierNummer": "506",
    "naam": "Glantier No. 506",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "506",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "507",
    "glantierNummer": "507",
    "naam": "Glantier No. 507",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "507",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "508",
    "glantierNummer": "508",
    "naam": "Glantier No. 508",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "508",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "509",
    "glantierNummer": "509",
    "naam": "Glantier No. 509",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Romantisch - Roos",
    "merkReferentie": "Chloe",
    "parfumReferentie": "Chloe",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een romantisch - roos karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "509",
      "chloe",
      "dames",
      "romantisch - roos"
    ]
  },
  {
    "id": "510",
    "glantierNummer": "510",
    "naam": "Glantier No. 510",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "510",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "511",
    "glantierNummer": "511",
    "naam": "Glantier No. 511",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "511",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "512",
    "glantierNummer": "512",
    "naam": "Glantier No. 512",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "512",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "513",
    "glantierNummer": "513",
    "naam": "Glantier No. 513",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "513",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "514",
    "glantierNummer": "514",
    "naam": "Glantier No. 514",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "514",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "515",
    "glantierNummer": "515",
    "naam": "Glantier No. 515",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Romantisch - Roos",
    "merkReferentie": "Chloe",
    "parfumReferentie": "Chloe",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een romantisch - roos karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "515",
      "chloe",
      "dames",
      "romantisch - roos"
    ]
  },
  {
    "id": "516",
    "glantierNummer": "516",
    "naam": "Glantier No. 516",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "516",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "517",
    "glantierNummer": "517",
    "naam": "Glantier No. 517",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "517",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "518",
    "glantierNummer": "518",
    "naam": "Glantier No. 518",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "518",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "519",
    "glantierNummer": "519",
    "naam": "Glantier No. 519",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "519",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "520",
    "glantierNummer": "520",
    "naam": "Glantier No. 520",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "520",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "521",
    "glantierNummer": "521",
    "naam": "Glantier No. 521",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Romantisch - Roos",
    "merkReferentie": "Chloe",
    "parfumReferentie": "Chloe",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een romantisch - roos karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "521",
      "chloe",
      "dames",
      "romantisch - roos"
    ]
  },
  {
    "id": "522",
    "glantierNummer": "522",
    "naam": "Glantier No. 522",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "522",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "523",
    "glantierNummer": "523",
    "naam": "Glantier No. 523",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "523",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "524",
    "glantierNummer": "524",
    "naam": "Glantier No. 524",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "524",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "525",
    "glantierNummer": "525",
    "naam": "Glantier No. 525",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "525",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "526",
    "glantierNummer": "526",
    "naam": "Glantier No. 526",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "526",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "527",
    "glantierNummer": "527",
    "naam": "Glantier No. 527",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Romantisch - Roos",
    "merkReferentie": "Chloe",
    "parfumReferentie": "Chloe",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een romantisch - roos karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "527",
      "chloe",
      "dames",
      "romantisch - roos"
    ]
  },
  {
    "id": "528",
    "glantierNummer": "528",
    "naam": "Glantier No. 528",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "528",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "529",
    "glantierNummer": "529",
    "naam": "Glantier No. 529",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "529",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "530",
    "glantierNummer": "530",
    "naam": "Glantier No. 530",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "530",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "531",
    "glantierNummer": "531",
    "naam": "Glantier No. 531",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "531",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "532",
    "glantierNummer": "532",
    "naam": "Glantier No. 532",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "532",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "533",
    "glantierNummer": "533",
    "naam": "Glantier No. 533",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Romantisch - Roos",
    "merkReferentie": "Chloe",
    "parfumReferentie": "Chloe",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een romantisch - roos karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "533",
      "chloe",
      "dames",
      "romantisch - roos"
    ]
  },
  {
    "id": "534",
    "glantierNummer": "534",
    "naam": "Glantier No. 534",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "534",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "535",
    "glantierNummer": "535",
    "naam": "Glantier No. 535",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "535",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "536",
    "glantierNummer": "536",
    "naam": "Glantier No. 536",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "536",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "537",
    "glantierNummer": "537",
    "naam": "Glantier No. 537",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "537",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "538",
    "glantierNummer": "538",
    "naam": "Glantier No. 538",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "538",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "539",
    "glantierNummer": "539",
    "naam": "Glantier No. 539",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Romantisch - Roos",
    "merkReferentie": "Chloe",
    "parfumReferentie": "Chloe",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een romantisch - roos karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "539",
      "chloe",
      "dames",
      "romantisch - roos"
    ]
  },
  {
    "id": "540",
    "glantierNummer": "540",
    "naam": "Glantier No. 540",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "540",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "541",
    "glantierNummer": "541",
    "naam": "Glantier No. 541",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "541",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "542",
    "glantierNummer": "542",
    "naam": "Glantier No. 542",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "542",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "543",
    "glantierNummer": "543",
    "naam": "Glantier No. 543",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "543",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "544",
    "glantierNummer": "544",
    "naam": "Glantier No. 544",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "544",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "546",
    "glantierNummer": "546",
    "naam": "Glantier No. 546",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Armani",
    "parfumReferentie": "Si",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "546",
      "armani",
      "dames",
      "luxe - amber",
      "si"
    ]
  },
  {
    "id": "547",
    "glantierNummer": "547",
    "naam": "Glantier No. 547",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "Dior",
    "parfumReferentie": "Miss Dior",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "547",
      "avond - intens",
      "dames",
      "dior",
      "miss dior"
    ]
  },
  {
    "id": "548",
    "glantierNummer": "548",
    "naam": "Glantier No. 548",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Chypre - Elegant",
    "merkReferentie": "Mugler",
    "parfumReferentie": "Alien",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een chypre - elegant karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "548",
      "alien",
      "chypre - elegant",
      "dames",
      "mugler"
    ]
  },
  {
    "id": "549",
    "glantierNummer": "549",
    "naam": "Glantier No. 549",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Fris - Bloemig",
    "merkReferentie": "Dior",
    "parfumReferentie": "J'adore",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - bloemig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "549",
      "dames",
      "dior",
      "fris - bloemig",
      "j'adore"
    ]
  },
  {
    "id": "550",
    "glantierNummer": "550",
    "naam": "Glantier No. 550",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Dames",
    "categorie": "Dames",
    "geurgroep": "Zoet - Fruitig",
    "merkReferentie": "Marc Jacobs",
    "parfumReferentie": "Daisy",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een zoet - fruitig karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "550",
      "daisy",
      "dames",
      "marc jacobs",
      "zoet - fruitig"
    ]
  },
  {
    "id": "701",
    "glantierNummer": "701",
    "naam": "Glantier No. 701",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Fris - Citrus",
    "merkReferentie": "Armani",
    "parfumReferentie": "Acqua di Gio",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - citrus karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "701",
      "acqua di gio",
      "armani",
      "fris - citrus",
      "heren"
    ]
  },
  {
    "id": "702",
    "glantierNummer": "702",
    "naam": "Glantier No. 702",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "702",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "703",
    "glantierNummer": "703",
    "naam": "Glantier No. 703",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "703",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "704",
    "glantierNummer": "704",
    "naam": "Glantier No. 704",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Kruidig - Warm",
    "merkReferentie": "Viktor & Rolf",
    "parfumReferentie": "Spicebomb",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een kruidig - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "704",
      "heren",
      "kruidig - warm",
      "spicebomb",
      "viktor & rolf"
    ]
  },
  {
    "id": "705",
    "glantierNummer": "705",
    "naam": "Glantier No. 705",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Creed",
    "parfumReferentie": "Aventus",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "705",
      "aventus",
      "creed",
      "heren",
      "luxe - amber"
    ]
  },
  {
    "id": "708",
    "glantierNummer": "708",
    "naam": "Glantier No. 708",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "708",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "709",
    "glantierNummer": "709",
    "naam": "Glantier No. 709",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "709",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "710",
    "glantierNummer": "710",
    "naam": "Glantier No. 710",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Kruidig - Warm",
    "merkReferentie": "Viktor & Rolf",
    "parfumReferentie": "Spicebomb",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een kruidig - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "710",
      "heren",
      "kruidig - warm",
      "spicebomb",
      "viktor & rolf"
    ]
  },
  {
    "id": "711",
    "glantierNummer": "711",
    "naam": "Glantier No. 711",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Creed",
    "parfumReferentie": "Aventus",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "711",
      "aventus",
      "creed",
      "heren",
      "luxe - amber"
    ]
  },
  {
    "id": "712",
    "glantierNummer": "712",
    "naam": "Glantier No. 712",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "YSL",
    "parfumReferentie": "Y Eau de Parfum",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "712",
      "avond - intens",
      "heren",
      "y eau de parfum",
      "ysl"
    ]
  },
  {
    "id": "713",
    "glantierNummer": "713",
    "naam": "Glantier No. 713",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Fris - Citrus",
    "merkReferentie": "Armani",
    "parfumReferentie": "Acqua di Gio",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - citrus karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "713",
      "acqua di gio",
      "armani",
      "fris - citrus",
      "heren"
    ]
  },
  {
    "id": "714",
    "glantierNummer": "714",
    "naam": "Glantier No. 714",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "714",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "715",
    "glantierNummer": "715",
    "naam": "Glantier No. 715",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "715",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "716",
    "glantierNummer": "716",
    "naam": "Glantier No. 716",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Kruidig - Warm",
    "merkReferentie": "Viktor & Rolf",
    "parfumReferentie": "Spicebomb",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een kruidig - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "716",
      "heren",
      "kruidig - warm",
      "spicebomb",
      "viktor & rolf"
    ]
  },
  {
    "id": "717",
    "glantierNummer": "717",
    "naam": "Glantier No. 717",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Creed",
    "parfumReferentie": "Aventus",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "717",
      "aventus",
      "creed",
      "heren",
      "luxe - amber"
    ]
  },
  {
    "id": "718",
    "glantierNummer": "718",
    "naam": "Glantier No. 718",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "YSL",
    "parfumReferentie": "Y Eau de Parfum",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "718",
      "avond - intens",
      "heren",
      "y eau de parfum",
      "ysl"
    ]
  },
  {
    "id": "719",
    "glantierNummer": "719",
    "naam": "Glantier No. 719",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Fris - Citrus",
    "merkReferentie": "Armani",
    "parfumReferentie": "Acqua di Gio",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - citrus karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "719",
      "acqua di gio",
      "armani",
      "fris - citrus",
      "heren"
    ]
  },
  {
    "id": "720",
    "glantierNummer": "720",
    "naam": "Glantier No. 720",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "720",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "721",
    "glantierNummer": "721",
    "naam": "Glantier No. 721",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "721",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "722",
    "glantierNummer": "722",
    "naam": "Glantier No. 722",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Kruidig - Warm",
    "merkReferentie": "Viktor & Rolf",
    "parfumReferentie": "Spicebomb",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een kruidig - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "722",
      "heren",
      "kruidig - warm",
      "spicebomb",
      "viktor & rolf"
    ]
  },
  {
    "id": "723",
    "glantierNummer": "723",
    "naam": "Glantier No. 723",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Creed",
    "parfumReferentie": "Aventus",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "723",
      "aventus",
      "creed",
      "heren",
      "luxe - amber"
    ]
  },
  {
    "id": "725",
    "glantierNummer": "725",
    "naam": "Glantier No. 725",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Fris - Citrus",
    "merkReferentie": "Armani",
    "parfumReferentie": "Acqua di Gio",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - citrus karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "725",
      "acqua di gio",
      "armani",
      "fris - citrus",
      "heren"
    ]
  },
  {
    "id": "726",
    "glantierNummer": "726",
    "naam": "Glantier No. 726",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "726",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "727",
    "glantierNummer": "727",
    "naam": "Glantier No. 727",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "727",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "728",
    "glantierNummer": "728",
    "naam": "Glantier No. 728",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Kruidig - Warm",
    "merkReferentie": "Viktor & Rolf",
    "parfumReferentie": "Spicebomb",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een kruidig - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "728",
      "heren",
      "kruidig - warm",
      "spicebomb",
      "viktor & rolf"
    ]
  },
  {
    "id": "729",
    "glantierNummer": "729",
    "naam": "Glantier No. 729",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Creed",
    "parfumReferentie": "Aventus",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "729",
      "aventus",
      "creed",
      "heren",
      "luxe - amber"
    ]
  },
  {
    "id": "730",
    "glantierNummer": "730",
    "naam": "Glantier No. 730",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "YSL",
    "parfumReferentie": "Y Eau de Parfum",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "730",
      "avond - intens",
      "heren",
      "y eau de parfum",
      "ysl"
    ]
  },
  {
    "id": "731",
    "glantierNummer": "731",
    "naam": "Glantier No. 731",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Fris - Citrus",
    "merkReferentie": "Armani",
    "parfumReferentie": "Acqua di Gio",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - citrus karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "731",
      "acqua di gio",
      "armani",
      "fris - citrus",
      "heren"
    ]
  },
  {
    "id": "732",
    "glantierNummer": "732",
    "naam": "Glantier No. 732",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "732",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "733",
    "glantierNummer": "733",
    "naam": "Glantier No. 733",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "733",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "734",
    "glantierNummer": "734",
    "naam": "Glantier No. 734",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Kruidig - Warm",
    "merkReferentie": "Viktor & Rolf",
    "parfumReferentie": "Spicebomb",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een kruidig - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "734",
      "heren",
      "kruidig - warm",
      "spicebomb",
      "viktor & rolf"
    ]
  },
  {
    "id": "735",
    "glantierNummer": "735",
    "naam": "Glantier No. 735",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Creed",
    "parfumReferentie": "Aventus",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "735",
      "aventus",
      "creed",
      "heren",
      "luxe - amber"
    ]
  },
  {
    "id": "736",
    "glantierNummer": "736",
    "naam": "Glantier No. 736",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "YSL",
    "parfumReferentie": "Y Eau de Parfum",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "736",
      "avond - intens",
      "heren",
      "y eau de parfum",
      "ysl"
    ]
  },
  {
    "id": "737",
    "glantierNummer": "737",
    "naam": "Glantier No. 737",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Fris - Citrus",
    "merkReferentie": "Armani",
    "parfumReferentie": "Acqua di Gio",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een fris - citrus karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "737",
      "acqua di gio",
      "armani",
      "fris - citrus",
      "heren"
    ]
  },
  {
    "id": "738",
    "glantierNummer": "738",
    "naam": "Glantier No. 738",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "738",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "739",
    "glantierNummer": "739",
    "naam": "Glantier No. 739",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "739",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "740",
    "glantierNummer": "740",
    "naam": "Glantier No. 740",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Kruidig - Warm",
    "merkReferentie": "Viktor & Rolf",
    "parfumReferentie": "Spicebomb",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een kruidig - warm karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "740",
      "heren",
      "kruidig - warm",
      "spicebomb",
      "viktor & rolf"
    ]
  },
  {
    "id": "741",
    "glantierNummer": "741",
    "naam": "Glantier No. 741",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Luxe - Amber",
    "merkReferentie": "Creed",
    "parfumReferentie": "Aventus",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een luxe - amber karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "741",
      "aventus",
      "creed",
      "heren",
      "luxe - amber"
    ]
  },
  {
    "id": "742",
    "glantierNummer": "742",
    "naam": "Glantier No. 742",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Avond - Intens",
    "merkReferentie": "YSL",
    "parfumReferentie": "Y Eau de Parfum",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een avond - intens karakter.",
    "moment": "Overdag en avond",
    "zoektermen": [
      "742",
      "avond - intens",
      "heren",
      "y eau de parfum",
      "ysl"
    ]
  },
  {
    "id": "744",
    "glantierNummer": "744",
    "naam": "Glantier No. 744",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Sportief - Aquatisch",
    "merkReferentie": "Chanel",
    "parfumReferentie": "Allure Homme Sport",
    "premiumBeschikbaar": false,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een sportief - aquatisch karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "744",
      "allure homme sport",
      "chanel",
      "heren",
      "sportief - aquatisch"
    ]
  },
  {
    "id": "745",
    "glantierNummer": "745",
    "naam": "Glantier No. 745",
    "type": "Parfum standaard EDP",
    "inhoud": "50 ml",
    "doelgroep": "Heren",
    "categorie": "Heren",
    "geurgroep": "Houtachtig - Droog",
    "merkReferentie": "Hermes",
    "parfumReferentie": "Terre d'Hermes",
    "premiumBeschikbaar": true,
    "prijs": 13,
    "image": "assets/images/glantier-heren-houtachtig.jpg",
    "omschrijving": "Een zorgvuldig geselecteerd Glantier geurprofiel met een houtachtig - droog karakter.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "745",
      "heren",
      "hermes",
      "houtachtig - droog",
      "terre d'hermes"
    ]
  },
  {
    "id": "sample-15ml-dames",
    "glantierNummer": "",
    "naam": "Glantier 15 ml Dames",
    "type": "Parfum standaard EDP",
    "inhoud": "15 ml",
    "doelgroep": "Dames",
    "categorie": "15 ml",
    "geurgroep": "Compact - Ontdekken",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 6,
    "image": "assets/images/glantier-15ml-dames.png",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "15 ml",
      "travel",
      "dames"
    ]
  },
  {
    "id": "sample-15ml-heren",
    "glantierNummer": "",
    "naam": "Glantier 15 ml Heren",
    "type": "Parfum standaard EDP",
    "inhoud": "15 ml",
    "doelgroep": "Heren",
    "categorie": "15 ml",
    "geurgroep": "Compact - Ontdekken",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 6,
    "image": "assets/images/glantier-heren-citrus.jpg",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "15 ml",
      "travel",
      "heren"
    ]
  },
  {
    "id": "bodymist-refresh",
    "glantierNummer": "",
    "naam": "Glantier Bodymist Verfrissend",
    "type": "Bodymist verfrissend",
    "inhoud": "100 ml",
    "doelgroep": "Unisex",
    "categorie": "Bodymist",
    "geurgroep": "Fris - Licht",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 6,
    "image": "assets/images/glantier-dames-fris.jpg",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "bodymist",
      "verfrissend"
    ]
  },
  {
    "id": "bodymist-glow",
    "glantierNummer": "",
    "naam": "Glantier Bodymist Verhelderend",
    "type": "Bodymist verhelderend",
    "inhoud": "100 ml",
    "doelgroep": "Unisex",
    "categorie": "Bodymist",
    "geurgroep": "Zacht - Verzorgend",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 6,
    "image": "assets/images/glantier-dames-lifestyle.jpg",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "bodymist",
      "verhelderend"
    ]
  },
  {
    "id": "box-8-50",
    "glantierNummer": "",
    "naam": "Glantier Parfum Box 8 ml + 50 ml",
    "type": "Parfum box",
    "inhoud": "8 ml + 50 ml",
    "doelgroep": "Unisex",
    "categorie": "Boxen",
    "geurgroep": "Cadeau - Luxe",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 24,
    "image": "assets/images/glantier-box-dames.png",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "box",
      "cadeau"
    ]
  },
  {
    "id": "box-5x15",
    "glantierNummer": "",
    "naam": "Glantier Parfum Box 5 x 15 ml",
    "type": "Parfum box",
    "inhoud": "5 x 15 ml",
    "doelgroep": "Unisex",
    "categorie": "Boxen",
    "geurgroep": "Cadeau - Ontdekken",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 22,
    "image": "assets/images/glantier-box-dames.png",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "box",
      "cadeau"
    ]
  },
  {
    "id": "geurstokjes-100",
    "glantierNummer": "",
    "naam": "Glantier Geurstokjes",
    "type": "Geurstokjes",
    "inhoud": "100 ml",
    "doelgroep": "Unisex",
    "categorie": "Geurstokjes",
    "geurgroep": "Interieur - Zacht",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 14,
    "image": "assets/images/glantier-geurstokjes.png",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "geurstokjes",
      "interieur"
    ]
  },
  {
    "id": "auto-hanger",
    "glantierNummer": "",
    "naam": "Glantier Auto Geurhanger",
    "type": "Auto geurhanger",
    "inhoud": "1 stuk",
    "doelgroep": "Unisex",
    "categorie": "Geurhangers",
    "geurgroep": "Auto - Fris",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 2.5,
    "image": "assets/images/glantier-geurstokjes.png",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "auto geurhanger"
    ]
  },
  {
    "id": "kast-hanger",
    "glantierNummer": "",
    "naam": "Glantier Kledingkast Geurhanger",
    "type": "Kledingkast geurhanger",
    "inhoud": "1 stuk",
    "doelgroep": "Unisex",
    "categorie": "Geurhangers",
    "geurgroep": "Textiel - Fris",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": false,
    "prijs": 3.5,
    "image": "assets/images/glantier-geurstokjes.png",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "kledingkast geurhanger"
    ]
  },
  {
    "id": "originals-100",
    "glantierNummer": "",
    "naam": "Glantier Originals Parfum",
    "type": "Glantier Originals Parfum",
    "inhoud": "100 ml",
    "doelgroep": "Unisex",
    "categorie": "Premium",
    "geurgroep": "Originals - Luxe",
    "merkReferentie": "",
    "parfumReferentie": "",
    "premiumBeschikbaar": true,
    "prijs": 25,
    "image": "assets/images/glantier-premium-dames.jpg",
    "omschrijving": "Een professioneel geselecteerd Glantier product voor luxe geurbeleving.",
    "moment": "Dagelijks gebruik",
    "zoektermen": [
      "originals",
      "premium"
    ]
  }
];
