export const plans={essential:{label:"Essential",discount:0,selections:1},signature:{label:"Signature",discount:10,selections:1},duo:{label:"Duo",discount:10,selections:2}};
export const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers}});
export const normalizeEmail=value=>String(value||"").trim().toLowerCase();
export async function hash(value){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
export function db(env){if(!env.SCENT_CLUB_DB)throw new Error("SCENT_CLUB_DB binding ontbreekt");return env.SCENT_CLUB_DB}
export function cookie(request,name){const found=(request.headers.get("Cookie")||"").split(";").map(v=>v.trim()).find(v=>v.startsWith(`${name}=`));return found?decodeURIComponent(found.slice(name.length+1)):""}
export function sessionCookie(token,maxAge=1800){return`orivea_scent_session=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Lax; Path=/api/scent-club; Max-Age=${maxAge}`}
export const clearCookie=()=>"orivea_scent_session=; HttpOnly; Secure; SameSite=Lax; Path=/api/scent-club; Max-Age=0";
export function maskCode(code){const text=String(code);return`${"•".repeat(Math.max(4,text.length-4))}${text.slice(-4)}`}
export function cutoffOpen(member,env,now=new Date()){const days=Math.max(0,Number(env.SCENT_SELECTION_CUTOFF_DAYS||5));if(!member.next_renewal_at)return now.getDate()<=Number(env.SCENT_SELECTION_CUTOFF_DAY||20);const cutoff=new Date(member.next_renewal_at);cutoff.setUTCDate(cutoff.getUTCDate()-days);return now<=cutoff}
export function view(member,env){const plan=plans[member.plan]||plans.essential;return{first_name:member.first_name||"lid",member_code:maskCode(member.member_code),plan:plan.label,status:member.status,pending_action:member.pending_action||null,started_at:member.started_at||null,next_renewal_at:member.next_renewal_at||null,selection_mode:member.selection_mode,preference_gender:member.preference_gender||"Unisex",discount:plan.discount,selections_allowed:plan.selections,selection_open:cutoffOpen(member,env)}}
export async function loadSession(request,env){const token=cookie(request,"orivea_scent_session");if(!token)return null;return await db(env).prepare("SELECT m.*,s.csrf_token,s.token_hash FROM scent_club_sessions s JOIN scent_club_members m ON m.id=s.member_id WHERE s.token_hash=? AND s.expires_at>? AND m.blocked=0").bind(await hash(token),new Date().toISOString()).first()||null}
export function validCsrf(request,session){const value=request.headers.get("X-CSRF-Token")||"";return value.length>20&&value===session.csrf_token}
export async function event(env,memberId,type,metadata={}){await db(env).prepare("INSERT INTO scent_club_events(member_id,event_type,metadata,created_at) VALUES(?,?,?,?)").bind(memberId,type,JSON.stringify(metadata),new Date().toISOString()).run()}
export async function task(env,memberId,type,title,metadata={}){await db(env).prepare("INSERT INTO scent_club_tasks(member_id,task_type,title,metadata,created_at) VALUES(?,?,?,?,?)").bind(memberId,type,title,JSON.stringify(metadata),new Date().toISOString()).run()}
