(() => {
  const decisionsKey = "orivea_glantier_import_decisions";
  const decisions = JSON.parse(localStorage.getItem(decisionsKey) || "{}");
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
  const save = () => localStorage.setItem(decisionsKey, JSON.stringify(decisions));
  const setStatus = (message) => { document.querySelector("[data-import-status]").textContent = message; };

  Promise.all([fetch("../data/glantier-import-preview.json").then((response) => response.json()), fetch("../data/glantier-new-products.json").then((response) => response.json()), fetch("../data/glantier-import-report.json").then((response) => response.json())]).then(([preview, newProducts, report]) => {
    document.querySelector("[data-import-summary]").innerHTML = `<span><strong>${report.checked}</strong> gecontroleerd</span><span><strong>${report.matched}</strong> gematcht</span><span><strong>${report.ingredients_found}</strong> met ingrediënten</span><span><strong>${report.review_required}</strong> controle nodig</span><span><strong>${report.new_products_found}</strong> nieuw gevonden</span>`;
    document.querySelector("[data-import-rows]").innerHTML = preview.map((item) => {
      const conflict = Boolean(item.comparison?.review_required);
      const status = conflict ? "Verschil" : item.local_status === "not_in_orivea" ? "Nieuw product" : item.comparison?.safe_update_available ? "Nieuwe informatie" : "Gelijk";
      const localText = item.orivea ? `${escapeHtml(item.orivea.geurgroep)}<small>${escapeHtml(item.orivea.inhoud)} · ${escapeHtml(item.orivea.categorie)}</small>` : `<span class="import-status warning">Niet in ORIVÈA</span>`;
      return `<tr data-reference="${item.reference_number}"><td><strong>Glantier ${item.reference_number}</strong><a href="${escapeHtml(item.official.official_product_url)}" target="_blank" rel="noopener noreferrer">Officiële bron</a></td><td>${localText}</td><td>${escapeHtml(item.official.fragrance_family)}<small>${escapeHtml(item.official.fragrance_concentration)} · ingrediënten ${item.official.ingredients_status === "found" ? "gevonden" : "niet gevonden"}</small></td><td><span class="import-status ${conflict ? "conflict" : item.local_status === "not_in_orivea" ? "warning" : "safe"}">${status}</span></td><td><div class="import-actions"><button type="button" data-decision="accept">Accepteren</button><button type="button" data-decision="skip">Overslaan</button></div></td></tr>`;
    }).join("");
    document.querySelector("[data-new-products]").innerHTML = newProducts.length ? newProducts.map((item) => `<article><p class="eyebrow">${escapeHtml(item.status)}</p><h3>Glantier ${item.reference_number}</h3><p>${escapeHtml(item.official_product_name)}</p><dl><dt>Categorie</dt><dd>${escapeHtml(item.category)}</dd><dt>Prijs</dt><dd>Ontbreekt</dd><dt>Verkoop</dt><dd>Uitgeschakeld</dd></dl><div class="import-actions"><a href="${escapeHtml(item.official_product_url)}" target="_blank" rel="noopener noreferrer">Bekijken</a><button type="button" data-new-decision="import" data-reference="${item.reference_number}" ${item.status === "discontinued" ? "disabled" : ""}>Importeren</button><button type="button" data-new-decision="ignore" data-reference="${item.reference_number}">Niet opnemen</button></div></article>`).join("") : "<p>Geen nieuwe producten gevonden.</p>";
    document.querySelector("[data-price-rows]").innerHTML = newProducts.filter((item) => item.status !== "discontinued").map((item) => `<tr data-price-reference="${item.reference_number}"><td>${item.reference_number}</td><td>${escapeHtml(item.official_product_name)}</td><td><input type="number" min="0.01" step="0.01" data-price="discovery"></td><td><input type="number" min="0.01" step="0.01" data-price="signature"></td><td><input type="number" min="0.01" step="0.01" data-price="premium"></td><td><input type="checkbox" data-activate disabled aria-label="Glantier ${item.reference_number} activeren"></td></tr>`).join("") || '<tr><td colspan="6">Geen activeerbare producten zonder prijs.</td></tr>';

    document.addEventListener("click", (event) => {
      const decision = event.target.closest("[data-decision]");
      if (decision) { const reference = decision.closest("tr").dataset.reference; decisions[reference] = { decision: decision.dataset.decision, updated_at: new Date().toISOString() }; save(); decision.closest("tr").dataset.reviewed = "true"; }
      const newDecision = event.target.closest("[data-new-decision]");
      if (newDecision) { decisions[newDecision.dataset.reference] = { decision: newDecision.dataset.newDecision, updated_at: new Date().toISOString() }; save(); }
      if (event.target.closest("[data-accept-safe]")) { preview.filter((item) => !item.comparison?.review_required).forEach((item) => { decisions[item.reference_number] = { decision: "accept_safe", updated_at: new Date().toISOString() }; }); save(); document.querySelectorAll("[data-reference]").forEach((row) => row.dataset.reviewed = "true"); setStatus("Alle veilige wijzigingen zijn in de lokale reviewselectie opgenomen."); }
      if (event.target.closest("[data-export-review]")) { const blob = new Blob([JSON.stringify({ decisions, exported_at: new Date().toISOString() }, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "glantier-import-review.json"; link.click(); URL.revokeObjectURL(link.href); setStatus("Reviewbestand geëxporteerd. Er is niets automatisch gepubliceerd."); }
    });
    document.querySelectorAll("[data-price-reference]").forEach((row) => row.addEventListener("input", () => { const signature = Number(row.querySelector('[data-price="signature"]').value); const activate = row.querySelector("[data-activate]"); activate.disabled = !(signature > 0); if (!activate.disabled) decisions[row.dataset.priceReference] = { ...(decisions[row.dataset.priceReference] || {}), price_status: "ready_for_review", signature_price: signature, sale_enabled: false }; save(); }));
  }).catch((error) => setStatus(`Importdata kon niet worden geladen: ${error.message}`));
})();
